apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthcp
  labels:
    app: healthcp
    tenant: opsera
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: healthcp-dev.agent.opsera.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: healthcp
                port:
                  number: 80
