apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: healthcp-role
  labels:
    app: healthcp
    tenant: opsera
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: healthcp-rolebinding
  labels:
    app: healthcp
    tenant: opsera
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: healthcp-role
subjects:
  - kind: ServiceAccount
    name: healthcp
