apiVersion: v1
kind: Service
metadata:
  name: healthcp
  labels:
    app: healthcp
    tenant: opsera
spec:
  selector:
    app: healthcp
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
