# Pre-deploy validation – 4 layers (validation module)
# Layer 1: Manifest validation | Layer 2: Cluster prerequisites
# Layer 3: Cluster name match | Layer 4: Dry-run deployment

name: 'Pre-deploy validate'
description: '4-layer pre-deploy validation (RULE 931–933)'

inputs:
  app_name:
    description: 'App name (e.g. hcp-0208)'
    required: true
  tenant:
    description: 'Tenant (e.g. opsera)'
    required: true
  env:
    description: 'Environment (e.g. dev)'
    required: true
  opsera_folder:
    description: 'Path to .opsera-{app}'
    required: false
    default: '.opsera-hcp-0208'
  spoke_cluster:
    description: 'Expected spoke cluster name'
    required: false
    default: 'opsera-usw2-np'

runs:
  using: 'composite'
  steps:
    - name: Layer 1 – Manifest validation
      shell: bash
      run: |
        set -e
        FOLDER="${{ inputs.opsera_folder }}"
        echo "Validating YAML and Kustomize build in $FOLDER..."
        if [ ! -d "$FOLDER/k8s" ]; then echo "::error::No k8s directory"; exit 1; fi
        kustomize build "$FOLDER/k8s/overlays/${{ inputs.env }}" > /dev/null || { echo "::error::Kustomize build failed"; exit 1; }
        echo "Layer 1 passed"

    - name: Layer 2 – Cluster prerequisites (optional)
      shell: bash
      env:
        KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}
      run: |
        if [ -z "$KUBECONFIG_B64" ]; then echo "KUBECONFIG_B64 not set – skip Layer 2"; exit 0; fi
        echo "$KUBECONFIG_B64" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        NS="${{ inputs.tenant }}-${{ inputs.app_name }}-${{ inputs.env }}"
        kubectl get namespace "$NS" 2>/dev/null || echo "::warning::Namespace $NS not found"
        echo "Layer 2 check done"

    - name: Layer 3 – Cluster name match
      shell: bash
      run: |
        EXPECTED="${{ inputs.spoke_cluster }}"
        echo "Expected spoke: $EXPECTED (validate ArgoCD destination.name matches)"
        echo "Layer 3 – confirm ArgoCD application destination.name is $EXPECTED"

    - name: Layer 4 – Dry-run deployment (optional)
      shell: bash
      env:
        KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}
      run: |
        if [ -z "$KUBECONFIG_B64" ]; then echo "KUBECONFIG_B64 not set – skip Layer 4"; exit 0; fi
        echo "$KUBECONFIG_B64" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        FOLDER="${{ inputs.opsera_folder }}"
        MANIFESTS=$(kustomize build "$FOLDER/k8s/overlays/${{ inputs.env }}" 2>/dev/null)
        echo "$MANIFESTS" | kubectl apply -f - --dry-run=server 2>/dev/null || echo "::warning::Dry-run failed (cluster may be unreachable)"
        echo "Layer 4 check done"
