# ════════════════════════════════════════════════════════════════════════════
# HEALTHCP - Production Dockerfile
# Multi-stage build for React + Vite application
# Generated by Opsera Code-to-Cloud Enterprise v1.6
# RULE 74: Uses nginx-unprivileged for non-root security
# ════════════════════════════════════════════════════════════════════════════

# Stage 1: Build
FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files first for better layer caching
COPY package*.json ./
COPY bun.lockb* ./

# RULE 73: Use npm install --legacy-peer-deps (NOT npm ci)
RUN npm install --legacy-peer-deps

# Copy source code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Production
# RULE 74: Use nginx-unprivileged for runAsNonRoot security contexts
FROM nginxinc/nginx-unprivileged:alpine AS production

# Copy custom nginx config (listens on 8080 for non-root)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy built assets from builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Add healthcheck on port 8080
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1

# Expose port 8080 (non-privileged port)
EXPOSE 8080

# nginx-unprivileged runs as non-root by default
# No need for explicit USER directive
