apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: healthcp
spec:
  rules:
    - host: healthcp-dev.agent.opsera.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: healthcp
                port:
                  number: 80
