# ════════════════════════════════════════════════════════════════════════════
# TERRAFORM OUTPUTS - Values needed for GitHub Actions secrets
# Generated by Opsera Code-to-Cloud Enterprise v1.4
# ════════════════════════════════════════════════════════════════════════════

output "setup_instructions" {
  description = "Instructions for configuring GitHub repository"
  value       = <<-EOT
    
    ╔══════════════════════════════════════════════════════════════════════════╗
    ║  SETUP INSTRUCTIONS                                                       ║
    ╚══════════════════════════════════════════════════════════════════════════╝
    
    Add these secrets to your GitHub repository:
    
    gh secret set AWS_ROLE_ARN --body "${aws_iam_role.github_actions.arn}"
    
    Add these variables to your GitHub repository:
    
    gh variable set AWS_REGION --body "${var.aws_region}"
    gh variable set EKS_CLUSTER --body "${module.eks.cluster_name}"
    gh variable set ECR_REPOSITORY --body "healthcp"
    
    Configure kubeconfig:
    
    aws eks update-kubeconfig --name ${module.eks.cluster_name} --region ${var.aws_region}
    
  EOT
}
