apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opsera-healthcp-dev
  namespace: argocd
  labels:
    app: healthcp
    tenant: opsera
    environment: dev
    managed-by: opsera-c2c
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/Opsera-Test/healthcp.git
    targetRevision: main
    path: .opsera-healthcp/k8s/overlays/dev
  destination:
    name: opsera-usw2-np
    namespace: opsera-healthcp-dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
